{
  "formatVersion": "1.1",
  "component": {
    "group": "smjni.jnigen",
    "module": "annotations",
    "version": "3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "64udvpvxrvgrjp5tvfpccqkuda"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "annotations-3.1.jar",
          "url": "annotations-3.1.jar",
          "size": 1410,
          "sha512": "394aced2f26070c13293cd42bca114bbb75a7665eee3ed1e8f2bc7b4006cece8196ac9a66ee7945be59f8b8eba4e36e420120646f2f7daaf28002975d61869ea",
          "sha256": "f891ed2e060286ceaa2dfe66b2da6002a62acb6f2a57adfff68d59a054c31cb0",
          "sha1": "c3f6ea7c8b24c2508af770660ac303f685a1606c",
          "md5": "7e30361d39200d9c31ea7f8b34f6b652"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-3.1.jar",
          "url": "annotations-3.1.jar",
          "size": 1410,
          "sha512": "394aced2f26070c13293cd42bca114bbb75a7665eee3ed1e8f2bc7b4006cece8196ac9a66ee7945be59f8b8eba4e36e420120646f2f7daaf28002975d61869ea",
          "sha256": "f891ed2e060286ceaa2dfe66b2da6002a62acb6f2a57adfff68d59a054c31cb0",
          "sha1": "c3f6ea7c8b24c2508af770660ac303f685a1606c",
          "md5": "7e30361d39200d9c31ea7f8b34f6b652"
        }
      ]
    }
  ]
}
